### ISSUE TITLE
"List index out of range" crash

### ISSUE THREAD

**Issue by mekkablue** [FEDER-CO/Scrambler#3]
Just received a user report:

```python
Details:
Traceback (most recent call last):

 File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBase.py", line 505, in action_
   self.callback(sender)

 File "~/Library/Application Support/Glyphs/Plugins/Scrambler.glyphsPalette/Contents/Resources/plugin.py", line 72, in scramblerCallback_
   tab.append(random.choice(printableLayers))

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 277, in choice
   return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty

IndexError: list index out of range

App:2.6.5-1342 Plugin:(null)-(null) 
```

**Comment by mekkablue** [comment]
I believe you can fix this issue easily if you check for the emptiness of `currentLayers` and not just for it being `None`:

https://github.com/FEDER-CO/Scrambler/blob/2df5ef641b03bddd914478bf2a0246b10048d7d9/Scrambler.glyphsPalette/Contents/Resources/plugin.py#L54

Make this line:

```python
if not currentLayers:
```

Then you reduce the risk of passing an empty sequence to the random function. Personally, I would even add another check for `printableLayers` just before the randomisation call.

Also, consider cleaning up tab.layers first, especially potential control characters, especially newlines. Or at least add a check for `<GSControlLayer "newline">`, its `parent` being `<GSGlyph "None" with 0 layers>`.

**Comment by FEDER-CO** [comment]
Thanks Rainer, I modified it as you suggested but I didn't understand the check that you suggest for printableLayers nor "cleaning up tab.layers".
