### ISSUE TITLE
Not working on M1

### ISSUE THREAD

**Issue by albertomalossi** [FEDER-CO/Scrambler#4]
After installation, on app reopen: 'The bundle “Scrambler” couldn’t be loaded because it doesn’t contain a version for the current architecture.'

**Comment by FEDER-CO** [comment]
Are you having the same trouble with other scripts as well?
https://forum.glyphsapp.com/t/scripts-refusing-to-show-up-in-glyphs-3-on-m1-macbook/18349

**Comment by albertomalossi** [comment]
No, only this one. Or at least, only this one has this behavior
